apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: people-web-app
  labels:
    app: people-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-web-app
  template:
    metadata:
      labels:
        app: people-web-app
    spec:
      containers:
      - name: people-web-app
        image: iad.ocir.io/gse00013828/oracleimc/people-web-app:1.0
        env:
         - name: REACT_APP_API_BASE_URL
           value: "http://people-service"
        ports:
        - containerPort: 5000
          name: people-web-app
      imagePullSecrets:
       - name: ocirsecret
---
#People Service
apiVersion: v1
kind: Service
metadata:
  name: people-web-app
  labels:
    app: people-web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: people-web-app
